
#!/bin/bash
#PBS -q workq
#PBS -N xtra100
#PBS -P PR350
#PBS -o xtra100-out.txt
#PBS -e xtra100-err.txt
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l place=scatter:excl
#PBS -l walltime=70:00:00

export MPLBACKEND="agg"
export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:/home/smavak/TourExec/bin
# Run std
cd /scratch/smavak/revisiting-axelrod-second/src
        
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_extra_strategy.py 0 500 100
        
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_extra_strategy.py 1 500 100
        
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_extra_strategy.py 2 500 100
        
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_extra_strategy.py 3 500 100
        
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_extra_strategy.py 4 500 100
        