
#!/bin/bash
#PBS -q workq
#PBS -N play-full
#PBS -P PR350
#PBS -o play-full-out.txt
#PBS -e play-full-err.txt
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l place=scatter:excl
#PBS -l walltime=70:00:00

export MPLBACKEND="agg"
export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:/home/smavak/TourExec/bin
# Run std
cd /scratch/smavak/revisiting-axelrod-second/src

/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 0 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 1 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 2 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 3 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 4 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 5 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 6 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 7 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 8 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_trained_strategy.py 9 250 ./data/training_strategies/training_data_original_tournament_full_players_with_axl.csv
