#!/bin/bash
#PBS -q workq
#PBS -N org2py
#PBS -P PR350
#PBS -o org2.txt
#PBS -e org2.txt
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l place=scatter:excl
#PBS -l walltime=70:00:00

export MPLBACKEND="agg"
export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:/home/smavak/TourExec/bin
# Run std
cd /scratch/smavak/revisiting-axelrod-second/src
/home/smavak/anaconda3/envs/rrr-axl/bin/python run_original_tournament_with_python_champion.py 2 1000
